name: lzf_music
description: "A new Flutter project."
publish_to: 'none'
version: 0.3.9

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  file_picker: ^10.2.0
  drift: ^2.28.0
  sqlite3_flutter_libs: ^0.5.40
  audio_metadata_reader:
    git:
      url: https://github.com/GerryDush/audio_metadata_reader.git
      ref: v0.0.9
  path_provider: ^2.1.2
  provider: ^6.1.5
  media_kit: ^1.1.11
  media_kit_libs_audio: ^1.0.7
  window_manager: ^0.5.1
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  bitsdojo_window: ^0.1.6
  audio_service:
     git:
      url: https://github.com/GerryDush/audio_service.git
      ref: v0.0.1
      path: audio_service
  audio_service_win:
     git:
      url: https://github.com/GerryDush/audio_service_win.git
      ref: main
  tray_manager: ^0.5.1
  crypto: ^3.0.0
  flutter_colorpicker: ^1.1.0
  flutter_acrylic: ^1.1.4
  flutter_localization: ^0.3.3
  xml: ^6.6.1
  palette_generator: ^0.3.3+7
  oklch: ^0.0.3
  flutter_svg: ^2.0.0
  cupertino_icons: ^1.0.8
  saf_stream: ^0.12.3
  saf_util:
    git:
      url: https://github.com/GerryDush/saf_util.git
      ref: v0.0.2
  http: ^0.13.6
  flutter_displaymode: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.14.1
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  fonts:
    - family: SFIcons
      fonts:
        - asset: assets/fonts/sf_icons.ttf
  assets:
    - assets/LICENSE
    - assets/icons/
    - assets/windows/icons/